joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

front_left_steering_controller: 
  type: effort_controllers/JointPositionController
  joint: front_left_shaft_joint
  pid : {p: 20.0 , i: 0.0 , d: 5.0}

front_right_steering_controller: 
  type: effort_controllers/JointPositionController
  joint: front_right_shaft_joint
  pid : {p: 20.0 , i: 0.0 , d: 5.0}

rear_left_wheel_controller: 
  type: effort_controllers/JointVelocityController
  joint: rear_left_wheel_joint
  pid : {p: 200.0 , i: 0.0 , d: 0.0}
    
rear_right_wheel_controller: 
  type: effort_controllers/JointVelocityController
  joint: rear_right_wheel_joint
  pid : {p: 200.0 , i: 0.0 , d: 0.0}